name: Feature Request
description: Let us know what you want!
title: "[Request]: "
labels: ["enhancement"]
projects: ["ordercloud-api/4"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your ideas!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: What is your request or idea?
      description: Has this already been requested?
      placeholder: No bad ideas here!
      value: "It would be awesome if..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.sitecore.com/legal/compliance). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
