name: Draft Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # manual trigger

jobs:
  build_test_pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      
    # Compare version from csproj with latest release tag.
    # If different, create a draft release.
      
    - name: Get csproj version
      id: csproj_ver
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
        file: src/OrderCloud.SDK/OrderCloud.SDK.csproj
        
    - name: Get latest release tag
      id: release_ver
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }} #required to see drafts
        exclude_types: prerelease
        view_top: 1
        
    - name: Output versions
      run: |
        echo "csproj version: ${{ steps.csproj_ver.outputs.version }}"
        echo "latest release: ${{ steps.release_ver.outputs.tag_name }}"
      
    - name: Draft release
      env:
        CSPROJ_VER: ${{ steps.csproj_ver.outputs.version }}
        RELEASE_VER: ${{ steps.release_ver.outputs.tag_name }}
      if: env.CSPROJ_VER != env.RELEASE_VER
      uses: ncipollo/release-action@v1.10.0
      with:
        tag: ${{ env.CSPROJ_VER }}
        body: "- Updates for latest OrderCloud API version"
        artifacts: "**/*.nupkg"
        draft: true
