name: Publish

on:
  release:
    types: [published]
  workflow_dispatch: #manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Download package
        uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          filename: "*.nupkg"
          token: ${{ github.token }}
          
      - name: Publish to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json --skip-duplicate
